# Generated by Django 4.2.11 on 2024-04-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
                ('transmission', models.CharField(choices=[('механика', 'Механическая'), ('автомат', 'Автоматическая'), ('АКПП', 'АКПП'), ('Робот', 'Робот'), ('Вариатор', 'Вариатор')], max_length=30)),
                ('mileage', models.IntegerField()),
                ('fuel', models.CharField(choices=[('Дизель', 'Дизель'), ('Бензин', 'Бензин'), ('Электро', 'Электро'), ('Гибрид', 'Гибрид'), ('ГБО', 'ГБО')], max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='car_images')),
            ],
        ),
    ]
